### ISSUE TITLE
error fetching features: Request failed with status 502

### ISSUE THREAD

**Issue by FabianHM** [thovid/ioBroker.viessmannapi#42]
Hallo Thomas,

hier eine weitere neuerliche Fehlermeldung:
`(2431) ViessmannClient: error fetching features: Request failed with status 502`
Ein Neustart des Adapters hat die Meldung:

`(32716) could not connect with refresh token, please enter email and password on adapter admin page`
zur Folge.
Ich verstehe nicht wie es zu den Meldungen kommt, da an den Daten nichts verändert wurde.

Wäre klasse wenn Du sagen könntest was die Meldungen bedeuten.

Danke und Grüße
Fabian

**Comment by FabianHM** [comment]
Anscheinend waren die Logindaten im Adapter weg.
Erst nachdem ich die Logindaten erneut eingegeben habe wurde der Adapter wieder grü.

Hängt das Verschwinden der Daten evtl. mit dem JS Controller zusammen?

**Comment by Ilovegym66** [comment]
Bei mir kommt die Fehlermeldung seit heute vormittag dauernd, ich bekomm den adapter nicht mehr grün. Logindaten sind richtig, sind auch eingetragen, habe von gestern auf heute nichts geändert.

**Comment by FabianHM** [comment]
Tja, schade dass anscheinend so wenig Leute diesen genialen Adapter nutzen und der Entwickler des Projekts nicht mehr reagiert.... und das wo die Heizsaison begonnen hat

**Comment by Ilovegym66** [comment]
habs rausgefunden, anscheinend hat Viessmann da was geaendert..  auf dem gleichen Rechner wo iobroker drauf läuft ein browser aufmachen, auf der Seite bei Viessmann einloggen, und seitdem gehts wieder... hmm

**Comment by FabianHM** [comment]
bin gespannt wie lange es läuft. Wird doch lediglich ein Cookie sein, oder?

**Comment by FabianHM** [comment]
Heute schon wieder ganzen Abend nur "Request failed with status 502" Fehlermeldungen....
@thovid: Könntest Du bitte das Thema vielleicht mal anschauen? 
Vielen Dank im Voraus!

**Comment by thovid** [comment]
Hallo, bin seit einer Weile dran, um zu verstehen, was das sein könnte. So richtig kann ich das Problem nicht nachvollziehen. Bei mir treten die Fehlermeldungen nicht auf. Grundsätzlich bedeutet der Status 502, das der Server von Viessmann ein Problem hat, ich hatte das mal vor längerer Zeit, als die Vitoconnect Box nicht im WLAN war. Hast du mal überprüft, ob du über die Viessmann App auf die Heizung zugreifen kannst? Sind die Status LEDs an der Vitoconnect Box alle ok?

Für die weitere Untersuchung wären ein paar zusätzliche Informationen hilfreich: 
- Unter welcher nodejs Version läuft dein ioBroker?
- Welche Version von ioBroker setzt du ein?
- Tritt der Fehler dauerhaft auf, oder kann sich der Adapter zwischendurch verbinden?
- Kannst Du den Adapter auf debug stellen und die Logeinträge hier an hängen, von einem Zeitpunkt an dem die Fehlermeldung kommt?

**Comment by FabianHM** [comment]
> 
> 
> Hallo, bin seit einer Weile dran, um zu verstehen, was das sein könnte. So richtig kann ich das Problem nicht nachvollziehen. Bei mir treten die Fehlermeldungen nicht auf. Grundsätzlich bedeutet der Status 502, das der Server von Viessmann ein Problem hat, ich hatte das mal vor längerer Zeit, als die Vitoconnect Box nicht im WLAN war. 

Hast du mal überprüft, ob du über die Viessmann App auf die Heizung zugreifen kannst?
**Ja, Zugriff funktioniert. Die App zeigt neuerdings sogar die WLAN Stärke in dbm an. Leider wird der Wert nicht über die States übertargem sonst könnte man die Fehlerquelle auch gut erkennen. Die App bietet sogar einen Neustart des VitoConnect Gateways an. Habe ich gerade bei aktiviertem Debug vesucht. Selbst damit lässt sich der Fehler 502 nicht reproduzieren.**

 Sind die Status LEDs an der Vitoconnect Box alle ok?
> Ja, alle leuchten grün
> Für die weitere Untersuchung wären ein paar zusätzliche Informationen hilfreich:
> 
>     * Unter welcher nodejs Version läuft dein ioBroker?
**Node.js: v10.17.0**

>     * Welche Version von ioBroker setzt du ein?
**NPM: 6.11.3; ioBroker.admin 3.6.12; JS controller: 2.0.39;**
> 
>     * Tritt der Fehler dauerhaft auf, oder kann sich der Adapter zwischendurch verbinden?
**Der Fehler tritt täglich, zu unterschiedenen Zeiten auf.** 
> 
>     * Kannst Du den Adapter auf debug stellen und die Logeinträge hier an hängen, von einem Zeitpunkt an dem die Fehlermeldung kommt?
**Debug eingestellt, Ergebnis poste ich morgen wenn entsprechende Einträge vorliegen.**

Danke für Deine feedback Thomas!

**Comment by FabianHM** [comment]
So, ich habe nun einige Tests hinsichtlich WLAN gemacht. Bei einem simulierten Abbruch des WLANS bzw extrem schlechtem Empfang konnte ich zu keiner Zeit den Request failed status 502 nachstellen. 
Wie mir jedoch aufgefallen ist, scheint der Vitoconnect 100 ziemlich anspruchsvoll in Sachen WLAn zu sein. Die App zeigt folgendes an:
![viessmann](https://user-images.githubusercontent.com/26110738/68790074-ea80ac00-0646-11ea-98a7-557e9ec01455.jpg)
Gibt es in den Features, die der Server zurück gibt, eine Möglichkeit die Werte der App auszugeben? Wäre zur Analyse sehr hilfreich.
In diesem Zusammenhang noch eine Frage:
Siehst Du eine Möglickeit über eine 

> sendTo('viessmannapi.0', 'action',
 
die Funktion "Gateway neustarten" analog der App auszulösen?

Danke und Grüße
Fabian

**Comment by FabianHM** [comment]
Fehler war zuletzt nicht mehr reproduzierbar.

**Comment by serecords** [comment]
Hier nochmal ein aktuelles Log welches den Fehler reproduziert.

Problem scheint zu sein, dass der refreshtoken nicht vom Server akzeptiert wird.

`2021-02-04 12:39:07.507  - [32minfo[39m: host.Bosmon-Server "system.adapter.viessmannapi.0" enabled
2021-02-04 12:39:07.518  - [32minfo[39m: host.Bosmon-Server instance system.adapter.viessmannapi.0 started with pid 14988
2021-02-04 12:39:08.506  - [34mdebug[39m: viessmannapi.0 (14988) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-02-04 12:39:08.522  - [34mdebug[39m: viessmannapi.0 (14988) Objects client ready ... initialize now
2021-02-04 12:39:08.525  - [34mdebug[39m: viessmannapi.0 (14988) Objects create System PubSub Client
2021-02-04 12:39:08.525  - [34mdebug[39m: viessmannapi.0 (14988) Objects create User PubSub Client
2021-02-04 12:39:08.525  - [34mdebug[39m: viessmannapi.0 (14988) Objects client initialize lua scripts
2021-02-04 12:39:08.530  - [34mdebug[39m: viessmannapi.0 (14988) Objects connected to redis: 127.0.0.1:9001
2021-02-04 12:39:08.533  - [34mdebug[39m: viessmannapi.0 (14988) objectDB connected
2021-02-04 12:39:08.535  - [34mdebug[39m: viessmannapi.0 (14988) Redis States: Use Redis connection: 127.0.0.1:9000
2021-02-04 12:39:08.537  - [34mdebug[39m: viessmannapi.0 (14988) States create User PubSub Client
2021-02-04 12:39:08.538  - [34mdebug[39m: viessmannapi.0 (14988) States create System PubSub Client
2021-02-04 12:39:08.541  - [34mdebug[39m: viessmannapi.0 (14988) States connected to redis: 127.0.0.1:9000
2021-02-04 12:39:08.541  - [34mdebug[39m: viessmannapi.0 (14988) statesDB connected
2021-02-04 12:39:08.581  - [32minfo[39m: viessmannapi.0 (14988) starting. Version 1.3.3 in C:/iobroker/node_modules/iobroker.viessmannapi, node: v10.15.0, js-controller: 3.1.6
2021-02-04 12:39:08.588  - [32minfo[39m: viessmannapi.0 (14988) starting adapter...
2021-02-04 12:39:08.596  - [32minfo[39m: viessmannapi.0 (14988) found email and password in configuration, deleting it due to security reasons. Adapter should restart now
2021-02-04 12:39:08.596  - [32minfo[39m: viessmannapi.0 (14988) authenticating with refresh token
2021-02-04 12:39:08.596  - [32minfo[39m: viessmannapi.0 (14988) ViessmannClient: initializing with pollIntervall 64000
2021-02-04 12:39:08.597  - [34mdebug[39m: viessmannapi.0 (14988) OAuthClient: initializing client
2021-02-04 12:39:08.597  - [34mdebug[39m: viessmannapi.0 (14988) OAuthClient: requesting initial access token using refreshToken=5c300dc334336c6c0b89d58a1ce4b752
2021-02-04 12:39:08.638  - [32minfo[39m: host.Bosmon-Server stopInstance system.adapter.viessmannapi.0 (force=false, process=true)
2021-02-04 12:39:08.638  - [32minfo[39m: host.Bosmon-Server stopInstance system.adapter.viessmannapi.0 send kill signal
2021-02-04 12:39:08.639  - [32minfo[39m: viessmannapi.0 (14988) Got terminate signal TERMINATE_YOURSELF
2021-02-04 12:39:08.639  - [32minfo[39m: viessmannapi.0 (14988) terminating
2021-02-04 12:39:08.640  - [32minfo[39m: viessmannapi.0 (14988) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-02-04 12:39:08.759  - [34mdebug[39m: viessmannapi.0 (14988) ViessmannClient: requesting installation details during initialization
2021-02-04 12:39:08.759  - [34mdebug[39m: viessmannapi.0 (14988) OAuthClient: GET https://api.viessmann-platform.io/general-management/installations - payload undefined
2021-02-04 12:39:09.076  - [31merror[39m: viessmannapi.0 (14988) error connecting: {"status":429}
2021-02-04 12:39:09.077  - [31merror[39m: viessmannapi.0 (14988) could not connect with refresh token, please enter email and password on adapter admin page
2021-02-04 12:39:09.158  - [32minfo[39m: host.Bosmon-Server instance system.adapter.viessmannapi.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-02-04 12:39:11.656  - [32minfo[39m: host.Bosmon-Server instance system.adapter.viessmannapi.0 started with pid 15316
2021-02-04 12:39:12.620  - [34mdebug[39m: viessmannapi.0 (15316) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-02-04 12:39:12.637  - [34mdebug[39m: viessmannapi.0 (15316) Objects client ready ... initialize now
2021-02-04 12:39:12.639  - [34mdebug[39m: viessmannapi.0 (15316) Objects create System PubSub Client
2021-02-04 12:39:12.640  - [34mdebug[39m: viessmannapi.0 (15316) Objects create User PubSub Client
2021-02-04 12:39:12.640  - [34mdebug[39m: viessmannapi.0 (15316) Objects client initialize lua scripts
2021-02-04 12:39:12.644  - [34mdebug[39m: viessmannapi.0 (15316) Objects connected to redis: 127.0.0.1:9001
2021-02-04 12:39:12.648  - [34mdebug[39m: viessmannapi.0 (15316) objectDB connected
2021-02-04 12:39:12.649  - [34mdebug[39m: viessmannapi.0 (15316) Redis States: Use Redis connection: 127.0.0.1:9000
2021-02-04 12:39:12.652  - [34mdebug[39m: viessmannapi.0 (15316) States create User PubSub Client
2021-02-04 12:39:12.653  - [34mdebug[39m: viessmannapi.0 (15316) States create System PubSub Client
2021-02-04 12:39:12.655  - [34mdebug[39m: viessmannapi.0 (15316) States connected to redis: 127.0.0.1:9000
2021-02-04 12:39:12.655  - [34mdebug[39m: viessmannapi.0 (15316) statesDB connected
2021-02-04 12:39:12.695  - [32minfo[39m: viessmannapi.0 (15316) starting. Version 1.3.3 in C:/iobroker/node_modules/iobroker.viessmannapi, node: v10.15.0, js-controller: 3.1.6
2021-02-04 12:39:12.702  - [32minfo[39m: viessmannapi.0 (15316) starting adapter...
2021-02-04 12:39:12.710  - [32minfo[39m: viessmannapi.0 (15316) ViessmannClient: initializing with pollIntervall 64000
2021-02-04 12:39:12.711  - [34mdebug[39m: viessmannapi.0 (15316) OAuthClient: initializing client
2021-02-04 12:39:12.711  - [34mdebug[39m: viessmannapi.0 (15316) OAuthClient: requesting initial access token using refreshToken=undefined
2021-02-04 12:39:12.849  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-04 12:39:12.849  - [31merror[39m: viessmannapi.0 (15316) unhandled promise rejection: Converting circular structure to JSON
2021-02-04 12:39:12.849  - [31merror[39m: viessmannapi.0 (15316) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at C:\iobroker\node_modules\iobroker.viessmannapi\dist\main.js:169:47
    at Generator.throw (<anonymous>)
    at rejected (C:\iobroker\node_modules\iobroker.viessmannapi\dist\main.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2021-02-04 12:39:12.853  - [32minfo[39m: viessmannapi.0 (15316) terminating
2021-02-04 12:39:12.853  - [32minfo[39m: viessmannapi.0 (15316) Terminated (NO_ERROR): Without reason
2021-02-04 12:39:13.372  - [32minfo[39m: host.Bosmon-Server instance system.adapter.viessmannapi.0 terminated with code 0 (NO_ERROR)
2021-02-04 12:39:13.373  - [32minfo[39m: host.Bosmon-Server Restart adapter system.adapter.viessmannapi.0 because enabled
2021-02-04 12:39:43.385  - [32minfo[39m: host.Bosmon-Server instance system.adapter.viessmannapi.0 started with pid 15852
2021-02-04 12:39:44.353  - [34mdebug[39m: viessmannapi.0 (15852) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-02-04 12:39:44.374  - [34mdebug[39m: viessmannapi.0 (15852) Objects client ready ... initialize now
2021-02-04 12:39:44.376  - [34mdebug[39m: viessmannapi.0 (15852) Objects create System PubSub Client
2021-02-04 12:39:44.377  - [34mdebug[39m: viessmannapi.0 (15852) Objects create User PubSub Client
2021-02-04 12:39:44.377  - [34mdebug[39m: viessmannapi.0 (15852) Objects client initialize lua scripts
2021-02-04 12:39:44.382  - [34mdebug[39m: viessmannapi.0 (15852) Objects connected to redis: 127.0.0.1:9001
2021-02-04 12:39:44.386  - [34mdebug[39m: viessmannapi.0 (15852) objectDB connected
2021-02-04 12:39:44.387  - [34mdebug[39m: viessmannapi.0 (15852) Redis States: Use Redis connection: 127.0.0.1:9000
2021-02-04 12:39:44.390  - [34mdebug[39m: viessmannapi.0 (15852) States create User PubSub Client
2021-02-04 12:39:44.391  - [34mdebug[39m: viessmannapi.0 (15852) States create System PubSub Client
2021-02-04 12:39:44.394  - [34mdebug[39m: viessmannapi.0 (15852) States connected to redis: 127.0.0.1:9000
2021-02-04 12:39:44.394  - [34mdebug[39m: viessmannapi.0 (15852) statesDB connected
2021-02-04 12:39:44.443  - [32minfo[39m: viessmannapi.0 (15852) starting. Version 1.3.3 in C:/iobroker/node_modules/iobroker.viessmannapi, node: v10.15.0, js-controller: 3.1.6
2021-02-04 12:39:44.450  - [32minfo[39m: viessmannapi.0 (15852) starting adapter...
2021-02-04 12:39:44.459  - [32minfo[39m: viessmannapi.0 (15852) ViessmannClient: initializing with pollIntervall 64000
2021-02-04 12:39:44.459  - [34mdebug[39m: viessmannapi.0 (15852) OAuthClient: initializing client
2021-02-04 12:39:44.460  - [34mdebug[39m: viessmannapi.0 (15852) OAuthClient: requesting initial access token using refreshToken=undefined
2021-02-04 12:39:44.591  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-04 12:39:44.591  - [31merror[39m: viessmannapi.0 (15852) unhandled promise rejection: Converting circular structure to JSON
2021-02-04 12:39:44.592  - [31merror[39m: viessmannapi.0 (15852) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at C:\iobroker\node_modules\iobroker.viessmannapi\dist\main.js:169:47
    at Generator.throw (<anonymous>)
    at rejected (C:\iobroker\node_modules\iobroker.viessmannapi\dist\main.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2021-02-04 12:39:44.595  - [32minfo[39m: viessmannapi.0 (15852) terminating
2021-02-04 12:39:44.595  - [32minfo[39m: viessmannapi.0 (15852) Terminated (NO_ERROR): Without reason
2021-02-04 12:39:45.116  - [32minfo[39m: host.Bosmon-Server instance system.adapter.viessmannapi.0 terminated with code 0 (NO_ERROR)
2021-02-04 12:39:45.116  - [32minfo[39m: host.Bosmon-Server Restart adapter system.adapter.viessmannapi.0 because enabled`
